version: "3.3"
services:
  reverse-proxy:
    image: traefik:v2.10.1
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    # container_name: "traefik"
    networks:
      - proxy
    command:
      - "--log.level=INFO"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--serversTransport.forwardingTimeouts.dialTimeout=2s"
      # - "--serverstransport.insecureskipverify=true"
    ports:
      - "80:80"
      # - "443:443"
      # - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reverse-proxy.rule=Host(`localhost`)"
      - "traefik.http.routers.reverse-proxy.service=api@internal"
      - "traefik.http.routers.reverse-proxy.entrypoints=web"
      # - "traefik.http.routers.reverse-proxy.tls=true"
      - "traefik.http.services.reverse-proxy.loadbalancer.server.port=8080"
      # - "traefik.http.middlewares.redirect-middleware.redirectscheme.scheme=https"
      # autenticacion
      - "traefik.http.routers.reverse-proxy.middlewares=dashboardauth"
      - "traefik.http.middlewares.dashboardauth.basicauth.users=admin:$$apr1$$FZq9oN4K$$RosIS9gkCzI0ybDgU0qIG0"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./configuration/:/configuration/

  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    networks:
      - proxy
    ports:
      - "9000:9000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./portainer-data:/data"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      # - traefik.http.routers.portainer-secure.tls=true
      - traefik.http.routers.portainer-secure.entrypoints=web
      - traefik.http.routers.portainer-secure.rule=Host(`portainer.example.com`)
      - traefik.http.routers.portainer-secure.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  proxy:
    driver: bridge
    external: true
