version: "3.3"

networks:
  proxy:
    driver: bridge
    external: true

services:
  whoami:
    image: traefik/whoami
    ports:
      - "8082:80"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.rule=HostSNI(`*`)"
      - "traefik.http.services.whoami-service.loadbalancer.server.port=80"

  nginx:
    image: nginx
    networks:
      - proxy
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.whoami.entrypoints=web"
      # - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      # - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx-service.loadbalancer.server.port=80"

  # coffee:
  #   image: sdaschner/quarkus-coffee:traefik-demo
  #   # container_name: coffee-$(date +%s)
  #   networks:
  #     - proxy
  #   labels:
  #     - "traefik.enable=true"
  #     # - "app=coffee"
  #     - "traefik.http.routers.coffee.rule=Host(`coffee.example.com`)"
  #     - "traefik.http.routers.coffee.tls=true"
  #     - "traefik.http.services.coffee-service.loadbalancer.server.port=8080"
  #     - "traefik.http.services.coffee-service.loadbalancer.healthcheck.path=/q/health"
  #     - "traefik.http.services.coffee-service.loadbalancer.healthcheck.interval=2s"
  #     - "traefik.http.services.coffee-service.loadbalancer.healthcheck.timeout=2s"
